Adding origin to NVTs
greenbone/gsa pull request #2588
Opened 2020-11-20 12:43 UTC by y0urself

**What**:

Adding the Severity Origin to the NVT Details.
* e.g. "Third Party"

**Why**:

**How**:

**Checklist**:

- [ ] Tests
- [ ] [CHANGELOG](https://github.com/greenbone/gsa/blob/master/CHANGELOG.md) Entry

2020-11-23 12:24 UTC, y0urself commented
![Uploading origin.png…]()

2020-11-23 12:24 UTC, y0urself commented
![origin](https://user-images.githubusercontent.com/15268273/99961721-2d637c80-2d8f-11eb-9a00-02a7242b0d3b.png)

2020-11-23 12:45 UTC, swaterkamp commented on gsa/src/gmp/models/nvt.js
> +      ret.severity_origin = parseText(severity.origin);
Please use camelCase for variables in GSA
```suggestion
      ret.severityOrigin = parseText(severity.origin);
```

2020-11-23 12:45 UTC, swaterkamp commented on gsa/src/web/pages/nvts/details.js
> +  const {tags = {}, severity, qod, family, solution, severity_origin} = entity;
```suggestion
  const {tags = {}, severity, qod, family, solution, severityOrigin} = entity;
```

2020-11-23 12:46 UTC, swaterkamp commented on gsa/src/web/pages/nvts/details.js
> +              <TableData>{na(severity_origin)}</TableData>
```suggestion
              <TableData>{na(severityOrigin)}</TableData>
```

2020-11-23 12:46 UTC, swaterkamp commented on CHANGELOG.md
> +- Added CVSS Origin to NVT Details Page [#2588](https://github.com/greenbone/gsa/pull/2588)
Please add the latest changes to the top of the list

2020-11-23 12:47 UTC, y0urself commented on gsa/src/web/pages/nvts/details.js
> +              <TableData>{na(severity_origin)}</TableData>
Sure ... 👍

2020-11-23 12:47 UTC, swaterkamp commented on CHANGELOG.md
> +- Added CVSS Origin to NVT Details Page [#2588](https://github.com/greenbone/gsa/pull/2588)
Same for line 12, I guess, so while your are at it... ;)

2020-11-24 11:36 UTC, swaterkamp commented on CHANGELOG.md
> +- Added CVSS Origin to NVT Details Page [#2588](https://github.com/greenbone/gsa/pull/2588)
```suggestion
- Added CVSS origin to NVT detailspage [#2588](https://github.com/greenbone/gsa/pull/2588)
```

2020-11-24 11:37 UTC, swaterkamp approved these changes

2020-11-24 11:38 UTC, swaterkamp commented on CHANGELOG.md
> +- Added CVSS origin to NVT detailspage [#2588](https://github.com/greenbone/gsa/pull/2588)
```suggestion
- Added CVSS origin to NVT details [#2588](https://github.com/greenbone/gsa/pull/2588)
```

2020-11-24 11:38 UTC, swaterkamp approved these changes

2020-11-24 12:39 UTC, sarahd93 requested changes
We need to adjust the tests for the nvt model. There is already a test "should parse severity" that can be renamed to "should parse severity from cvss_base". And we need a new test "should parse severity and severity origin" to make sure that works as well. If I understand it correctly in case we have severities and cvss_base defined we want to use the severities and not the cvss_base so the test should cover that as well.

2020-11-24 15:18 UTC, sarahd93 requested changes

2020-11-24 15:18 UTC, sarahd93 commented on gsa/src/gmp/models/__tests__/nvt.js
> +      },
```suggestion
      },
      cvss_base: '7.5'
```

2020-11-24 15:18 UTC, sarahd93 commented on gsa/src/gmp/models/__tests__/nvt.js
> +      },
We should add something like this to make sure that the cvss_base is ignored and the severity from severities is used. That is how it is supposed to work, right, we only use the cvss_base as a fall back?

2020-11-24 15:18 UTC, sarahd93 commented on gsa/src/gmp/models/__tests__/nvt.js
> +          origin: 'Third Party',
Can origin be undefined or empty? We should have one nvt in the test where we don't have an origin to make sure we can handle that correctly.

2020-11-24 15:40 UTC, sarahd93 approved these changes

2020-11-24 15:40 UTC, merged