Result empty sections
greenbone/gsa pull request #2791
Opened 2021-03-15 06:44 UTC by swaterkamp

**What**:
Adjust ceck for empty sections from `isDefined()` to `!isEmpty()` in accordance to new data.

**Why**:
Instead of undefined information we got an empty string. This fixes the check that we had in place before.

**How**:
Check data in dev-tools and visually inspect whether the sections are no longer visible if there is no information.

**Checklist**:

- [N/A] Tests
- [X] [CHANGELOG](https://github.com/greenbone/gsa/blob/master/CHANGELOG.md) Entry

2021-03-15 07:59 UTC, bjoernricks approved these changes
I am fine with this change too but could you please also fix the models to set undefined if an empty string is used in these tags. Such things should to be fixed in the parsing part (model) to avoid having to implement this meaning of empty string at several places in the view.

2021-03-15 07:59 UTC, bjoernricks requested changes
Clicked on the wrong item. Should have been a Request changes.

2021-03-26 11:58 UTC, bjoernricks requested changes

2021-03-26 11:58 UTC, bjoernricks commented on gsa/src/gmp/models/nvt.js
> +      const newValue = value === '' ? undefined : value;
```suggestion
      const newValue = isEmpty(value) ? undefined : value;
```

2021-04-06 15:01 UTC, sarahd93 submitted a review, later dismissed

2021-04-07 13:27 UTC, sarahd93 approved these changes

2021-04-07 13:33 UTC, merged