Remove solution from log NVTs
greenbone/gsa pull request #2792
Opened 2021-03-15 06:49 UTC by swaterkamp

**What**:
Remove solution from NVTs

**Why**:
Log NVTs don't have a solution anyways and this leads to a meaningless solution section in the details showing only a questionmark for solution type.

**How**:
Visual inspection and updatd test for NVT model

**Checklist**:

- [X] Tests
- [X] [CHANGELOG](https://github.com/greenbone/gsa/blob/master/CHANGELOG.md) Entry

2021-03-16 08:12 UTC, bjoernricks approved these changes

2021-03-16 08:43 UTC, sarahd93 requested changes
After discussing this we came to the conclusion that this is not the behaviour we actually want. Since some log results can have a solutiontype we do want to show the solution section in this case. But for undefined solution types the solution section should not be shown for log results as well as other severities.

2021-03-26 07:46 UTC, bjoernricks submitted a review, later dismissed

2021-03-26 07:46 UTC, bjoernricks commented on gsa/src/gmp/models/nvt.js
> +      }
Please keep the existing functions for such cases in mind and keep in mind we should have not several meanings for the same thing. No solution type, text, method should mean it has an undefined value.
```suggestion
      ret.solution = {
        type: isEmpty(solutionType) ? undefined : solutionType,
        description:  isEmpty(solutionText) ? undefined : solutionText,
        method: isEmpty(solutionMethod) ? undefined : solutionMethod,
      };
```

2021-04-06 15:01 UTC, sarahd93 submitted a review, later dismissed

2021-04-07 13:30 UTC, sarahd93 submitted a review, later dismissed

2021-04-07 13:40 UTC, sarahd93 approved these changes

2021-04-07 13:46 UTC, merged