Properly space and linebreak roles and groups in users table row
greenbone/gsa pull request #2949
Opened 2021-05-28 09:17 UTC by swaterkamp

**What**:
Properly space and linebreak roles and groups in users table row by not using the Divider component, which prevents wraps in flexbox. Instead add a `,&nbsp;` to each entry, except the last one, and let flexbox do it's magic (using the Layout component).

**Why**:
Adding too many roles and/or groups to a user grew the table row too wide and move parts of it out of screen. It was also not very readable even without growing > 100%/width

**How**:
Visually inspect how roles and groups are displayed.

**Checklist**:

- [N/A] Tests
- [X] [CHANGELOG](https://github.com/greenbone/gsa/blob/master/CHANGELOG.md) Entry
- [X] Labels for ports to other branches

2021-05-31 12:15 UTC, bjoernricks requested changes
> Properly space and linebreak roles and groups in users table row by not using the Divider component, which prevents wraps in flexbox. Instead add a ,&nbsp; to each entry, except the last one, and let flexbox do it's magic (using the Layout component).

Why not using the [wrap](https://css-tricks.com/snippets/css/a-guide-to-flexbox/#flex-wrap) prop at the divider?

2021-06-01 10:23 UTC, swaterkamp commented
This might be a slightly misleading commit message. The `<Divider>` is a `<Layout>` and should be able to handle the `wrap`, of course. When introducing the comma between the items, however, I used `<Layout>` instead, because otherwise I would have had to wrap each item and its comma into another span or so, to get the spacing right. Switching to `<Layout>` kept the component tree a bit simpler and easier to read.

2021-06-03 14:26 UTC, bjoernricks requested changes
For me your solutions looks to complicated. If this can't be fixed with CSS (especially flexbox) alone it should be abstracted into a Divider like component.

2021-06-04 09:12 UTC, swaterkamp commented
Using `,` is just making this so complicated. I now decided on using a wrappable HorizontalSep, to keep the solution as simple as possible.

2021-06-07 14:02 UTC, sarahd93 approved these changes

2021-06-07 14:04 UTC, merged