release-pontos: also create gsa-node-modules release artifact
greenbone/gsa pull request #3819
Opened 2023-07-28 12:30 UTC by Flowdalic

For Gentoo, we ideally want to build the node modules as part of our "emerge" process. That means we do not want to consume the -dist artifact. What we instead want is the gsa source and the contents of the node_modules/ directory.

Therefore, add a second release artifact to release-ponto, that only contains the content of the node_modules/ directory.

Please consider this addition, as it would reduce the friction of packaging gsa in Gentoo.

Note that this is untested, since I do not know how to test github workflows, but the change seems trivial enough.

2023-07-28 14:47 UTC, bjoernricks requested changes
Would be nice if you can change your commit message title to `Add: Also create gsa-node-modules release artifact`. In that case it gets included into the release changelog automatically.

I am curious why you are not using the dist files. It is for reproducibility?

2023-07-28 14:47 UTC, bjoernricks commented on .github/workflows/release-pontos.yml
> +          gh release upload ${{ needs.release.outputs.git-release-tag }} gsa-node-modules-${{ needs.release.outputs.release-version }}.tar.xz
The node modules should be uploaded additionally to the dist files.
```suggestion
          gh release upload ${{ needs.release.outputs.git-release-tag }} gsa-dist-${{ needs.release.outputs.release-version }}.tar.gz gsa-node-modules-${{ needs.release.outputs.release-version }}.tar.xz
```

2023-07-29 12:48 UTC, Flowdalic commented
> I am curious why you are not using the dist files. It is for reproducibility?

Mostly because [Gentoo likes to perform the `yarn build` step itself](https://github.com/gentoo/gentoo/blob/ec7630170f1f7c47826d6c0738f705ca516cf237/net-analyzer/gsa/gsa-22.5.3.ebuild#L41-L42). Granted, it is not the same as building C/C++ source, but the next best equivalent. This allows users to fine-tune the resulting packages and allows testing with different yarn versions, etc.

2023-08-04 11:53 UTC, bjoernricks commented
Doesn't really make much sense for us but anyway I am happy to support Gentoo here.

2023-08-04 11:53 UTC, bjoernricks approved these changes

2023-08-04 12:02 UTC, merged

2023-08-04 12:45 UTC, Flowdalic commented
> Doesn't really make much sense for us but anyway I am happy to support Gentoo here.

Thanks, your support is appreciated. :)