Add: CVSS 4.0 Calculator
greenbone/gsa pull request #4036
Opened 2024-05-31 08:15 UTC by daniele-mng

## What

This PR introduces the CVSS 4.0 Calculator under the `extras>CVSS Calculator` page

## Why

Since the new The CVSS 4.0 Calculator is now available, we need to update the CVSS Calculator page to reflect this change.

## References

GEA-530

## Checklist

- [ ] Tests

2024-06-03 09:04 UTC, timopollmeier requested changes

2024-06-03 09:04 UTC, timopollmeier commented on src/web/pages/extras/cvssV4Point0/utils.js
> +    return 0;
I think it would be better to return `undefined` or a value that's not in the valid 0.0 to 10.0 range so it can be used to detect errors.

2024-06-03 14:01 UTC, daniele-mng commented on src/web/pages/extras/cvssV4Point0/cvssConfig.js
> +        name: 'Integrity',
I made the changes and added `Impact` suffix.

2024-06-07 08:39 UTC, timopollmeier commented on public/locales/gsa-de.json
> +  "CVSSv4 Base Score Calculator": "CVSSv4 Basis-Score-Rechner",
```suggestion
  "CVSSv4 Score Calculator": "CVSSv4 Score-Rechner",
```

2024-06-07 08:43 UTC, timopollmeier approved these changes

2024-06-07 08:48 UTC, merged