Fix: Make report configs optional in alerts and reports
greenbone/gsa pull request #4104
Opened 2024-07-16 12:34 UTC by timopollmeier

## What
If the report configs are not available, the report export and alert dialogs will hide the report config fields.

## Why
This will make the dialogs work as expected if the report config commands are disabled.

## References
GEA-647

## Checklist

- [ ] Tests

2024-07-17 09:41 UTC, a-h-abdelsalam requested changes

2024-07-17 09:41 UTC, a-h-abdelsalam commented on src/web/pages/alerts/scpmethodpart.jsx
> +  capabilities,
I think it is better to use `useCapabilities` hook instead of passing it as a prop
```suggestion
```

2024-07-17 09:41 UTC, a-h-abdelsalam commented on src/web/pages/alerts/scpmethodpart.jsx
> +  capabilities: PropTypes.capabilities.isRequired,
```suggestion
```

2024-07-17 09:41 UTC, a-h-abdelsalam commented on src/web/pages/alerts/sendmethodpart.jsx
> +  capabilities: PropTypes.capabilities.isRequired,
```suggestion
```

2024-07-17 09:41 UTC, a-h-abdelsalam commented on src/web/pages/alerts/sendmethodpart.jsx
> +  capabilities,
Same here. You can use `useCapabilities` hook.
```suggestion
```

2024-07-17 09:41 UTC, a-h-abdelsalam commented on src/web/pages/alerts/smbmethodpart.jsx
> +  capabilities,
Here as well
```suggestion
```

2024-07-17 09:41 UTC, a-h-abdelsalam commented on src/web/pages/alerts/smbmethodpart.jsx
> +  capabilities: PropTypes.capabilities.isRequired,
```suggestion
```

2024-07-17 09:41 UTC, a-h-abdelsalam commented on src/web/pages/alerts/verinicemethodpart.jsx
> +  capabilities,
Here as well.
```suggestion
```

2024-07-17 09:41 UTC, a-h-abdelsalam commented on src/web/pages/alerts/verinicemethodpart.jsx
> +  capabilities: PropTypes.capabilities,
```suggestion
```

2024-07-17 09:41 UTC, a-h-abdelsalam commented on src/web/pages/alerts/emailmethodpart.jsx
> +                    capabilities.mayOp("get_report_configs") &&
I think it is better to replace passing `capabilities` as a prop with the `useCapabilities` hook. 

The export will need an update to remove `withCapabilities`

2024-07-17 09:41 UTC, a-h-abdelsalam commented on src/web/pages/alerts/dialog.jsx
> +                  capabilities={capabilities}
You can skip passing `capabilities` here for all the methods if you will go with the hook.
```suggestion
```

2024-07-17 09:41 UTC, a-h-abdelsalam commented on src/web/pages/alerts/dialog.jsx
> +                  capabilities={capabilities}
```suggestion
```

2024-07-17 09:41 UTC, a-h-abdelsalam commented on src/web/pages/alerts/dialog.jsx
> +                  capabilities={capabilities}
```suggestion
```

2024-07-17 09:41 UTC, a-h-abdelsalam commented on src/web/pages/alerts/dialog.jsx
> +                  capabilities={capabilities}
```suggestion
```

2024-07-17 16:23 UTC, daniele-mng commented on src/web/pages/alerts/emailmethodpart.jsx
> +                      <label htmlFor="report-config-select">Report Config</label>
Question: Could we use the `FormGroup` component wrapping `Select` component?

2024-07-22 09:55 UTC, a-h-abdelsalam commented on src/web/pages/alerts/emailmethodpart.jsx
> +import useCapabilities from "web/hooks/useCapabilities.js";
One small detail. You can drop the `.js` suffix
```suggestion
import useCapabilities from 'web/hooks/useCapabilities';
```

2024-07-22 09:55 UTC, a-h-abdelsalam commented on src/web/pages/alerts/sendmethodpart.jsx
> +import useCapabilities from "web/hooks/useCapabilities.js";
```suggestion
import useCapabilities from 'web/hooks/useCapabilities';
```

2024-07-22 09:55 UTC, a-h-abdelsalam commented on src/web/pages/alerts/smbmethodpart.jsx
> +import useCapabilities from "web/hooks/useCapabilities.js";
```suggestion
import useCapabilities from 'web/hooks/useCapabilities';
```

2024-07-22 09:55 UTC, a-h-abdelsalam commented on src/web/pages/alerts/verinicemethodpart.jsx
> +import useCapabilities from "web/hooks/useCapabilities.js";
```suggestion
import useCapabilities from 'web/hooks/useCapabilities';
```

2024-07-22 10:22 UTC, a-h-abdelsalam approved these changes

2024-07-22 11:23 UTC, merged